/* Generated by Yosys 0.9+932 (git sha1 4072a966, gcc 7.4.0-1ubuntu1~18.04.1 -fPIC -Os) */

(* generator = "nMigen" *)
(* top =  1  *)
(* \nmigen.hierarchy  = "top" *)
module top(INPUT__TVALID, INPUT__TREADY, INPUT__TLAST, OUTPUT__TDATA, OUTPUT__TVALID, OUTPUT__TREADY, OUTPUT__TLAST, INPUT__TDATA);
  (* src = "./test_case.py:20" *)
  input [15:0] INPUT__TDATA;
  (* src = "./test_case.py:20" *)
  input INPUT__TLAST;
  (* src = "./test_case.py:20" *)
  output INPUT__TREADY;
  (* src = "./test_case.py:20" *)
  input INPUT__TVALID;
  (* src = "./test_case.py:20" *)
  output [15:0] OUTPUT__TDATA;
  (* src = "./test_case.py:20" *)
  output OUTPUT__TLAST;
  (* src = "./test_case.py:20" *)
  input OUTPUT__TREADY;
  (* src = "./test_case.py:20" *)
  output OUTPUT__TVALID;
  assign INPUT__TREADY = OUTPUT__TREADY;
  assign OUTPUT__TLAST = INPUT__TLAST;
  assign OUTPUT__TVALID = INPUT__TVALID;
  assign OUTPUT__TDATA = INPUT__TDATA;
endmodule

